# Generated by Django 6.0.4 on 2026-04-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='valor_total',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.CharField(default='Geral', max_length=200),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('KG', 'Quilograma'), ('UN', 'Unidade'), ('LT', 'Litro'), ('MT', 'Metro'), ('PA', 'Pacote')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.CharField(default='Consumidor', max_length=200),
        ),
    ]
