# Generated by Django 6.0.4 on 2026-04-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_valor_total_venda_preco_venda_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_de_pagamento',
            field=models.CharField(default='Dinheiro', max_length=8),
        ),
    ]
