# Generated by Django 6.0.4 on 2026-04-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_venda_forma_de_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
    ]
