# Generated by Django 6.0.4 on 2026-04-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_venda_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(max_length=30),
        ),
    ]
