# Generated by Django 6.0.4 on 2026-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto_data_validade_alter_fornecedor_nome_fantasia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
