# Generated by Django 6.0.4 on 2026-04-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produto_codigo_barras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='preco',
            new_name='valorTotal',
        ),
    ]
