# Generated by Django 6.0.4 on 2026-04-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_preco_venda_valortotal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('vendas_dinheiro_sistema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dinheiro_em_caixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fundo_reserva_proximo_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_recolhido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sangrias', to='core.fechamentocaixa')),
            ],
        ),
    ]
