# Generated by Django 6.0.4 on 2026-05-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fechamentocaixa_sangria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(max_length=13, unique=True, verbose_name='Código de Barras'),
        ),
    ]
