# Generated by Django 6.0.4 on 2026-05-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_produto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(max_length=13, verbose_name='Código de Barras'),
        ),
    ]
