# Generated by Django 6.0.4 on 2026-05-02 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_produto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fator_conversao',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Ex: Se um pacote tem 15kg, o fator é 15.000', max_digits=10, verbose_name='Fator de Conversão'),
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_pai',
            field=models.ForeignKey(blank=True, help_text='Se for um item a granel, selecione o pacote original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_granel', to='core.produto', verbose_name='Pacote de Origem'),
        ),
    ]
