# Generated by Django 6.0.4 on 2026-05-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_produto_fator_conversao_produto_produto_pai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='observacoes',
        ),
    ]
